### PR TITLE
Added Storybook and Button

### LINKED ISSUE #21: Configure Storybook for the repository
**What needs to be done? Why does it need to be done?**
To organize the components, we’d like to adopt a tool called [Storybook](https://storybook.js.org/). This will allow us to easily test various component states, ensure that what we build is re-usable, and set us up to adopt the components across the organization.

Please review the [getting started guide](https://www.learnstorybook.com/intro-to-storybook/), set up Storybook, ensure that it runs for our repo.

### LINKED ISSUE #22: Create a `Button` component and add it to Storybook
**What needs to be done? Why does it need to be done?**
The props should allow for a bordered or borderless button and allow the contents to be changed

Screen Shot 2020-12-23 at 2 57 35 PM
Screen Shot 2020-12-23 at 2 57 40 PM

### PR DESCRIPTION
**Pull request by MeloncholyShiro**
## Description of the change

Added storybook, set it up for CRA + Typescript. Added one test component.
Checked how both Storybook and main project are built. Everything works.

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #21 
> Closes #22 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by ohaibbq** [comment]
Looking good! Could we remove the example Storybook components?

From there, we can take on #22 for our first component!

**Comment by MeloncholyShiro** [comment]
> 
> 
> Looking good! Could we remove the example Storybook components?
> 
> From there, we can take on #22 for our first component!

Done :)

**Review by ohaibbq — CHANGES_REQUESTED** [review]
I was able to run Storybook without any of the webfonts in `src/assets`. Do we need them?

Both non-primary buttons and primary buttons' text should align. Currently, the non-primary button is far shorter than the primary button.

Can we change the `color` prop to instead take an enum, for example `COLORS.PRIMARY` would give us the brand's green color, and `COLORS.WARNING`, would give us a red color.

**Comment by MeloncholyShiro** [comment]
@ohaibbq Removed unused assets, and made the buttons more uniform.
Please see if I understand you correctly about the buttons?

**Comment by ohaibbq** [comment]
Great! Last thing before approval: do you encounter this error when running `yarn run start`?
```yarn run v1.22.10
$ react-scripts start

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /Users/danhansen/workspace/case-triage/node_modules/babel-loader (version: 8.2.2)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-loader" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /Users/danhansen/workspace/case-triage/node_modules/babel-loader is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-loader in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-loader.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by MeloncholyShiro** [comment]
> 
> 
> Great! Last thing before approval: do you encounter this error when running `yarn run start`?
> 
> ```
> $ react-scripts start
> 
> There might be a problem with the project dependency tree.
> It is likely not a bug in Create React App, but something you need to fix locally.
> 
> The react-scripts package provided by Create React App requires a dependency:
> 
>   "babel-loader": "8.1.0"
> 
> Don't try to install it manually: your package manager does it automatically.
> However, a different version of babel-loader was detected higher up in the tree:
> 
>   /Users/danhansen/workspace/case-triage/node_modules/babel-loader (version: 8.2.2)
> 
> Manually installing incompatible versions is known to cause hard-to-debug issues.
> 
> If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
> That will permanently disable this message but you might encounter other issues.
> 
> To fix the dependency tree, try following the steps below in the exact order:
> 
>   1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
>   2. Delete node_modules in your project folder.
>   3. Remove "babel-loader" from dependencies and/or devDependencies in the package.json file in your project folder.
>   4. Run npm install or yarn, depending on the package manager you use.
> 
> In most cases, this should be enough to fix the problem.
> If this has not helped, there are a few other things you can try:
> 
>   5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
>      This may help because npm has known issues with package hoisting which may get resolved in future versions.
> 
>   6. Check if /Users/danhansen/workspace/case-triage/node_modules/babel-loader is outside your project directory.
>      For example, you might have accidentally installed something in your home folder.
> 
>   7. Try running npm ls babel-loader in your project folder.
>      This will tell you which other package (apart from the expected react-scripts) installed babel-loader.
> 
> If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
> That would permanently disable this preflight check in case you want to proceed anyway.
> 
> P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```
> ```

Sorry, my mistake. Fixed!

**Review by ohaibbq — APPROVED** [review]

**Pull request merged**
