### PR TITLE
Add GH Action to publish package

### PR DESCRIPTION
**Pull request by nbhargava**
## Description of the change

This PR attempts to add a workflow that publishes a new release to GitHub Packages on every merge to master. It uses a [community marketplace app](https://github.com/marketplace/actions/automated-releases-for-npm-packages) to perform the version bump update on each push to master and largely follows its example.

The details in [this link](https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-github-packages) is used to try to verify that the correct variables are being set for publishing to GitHub Packages instead of npm.

Our caching strategy is the same as in the recidiviz-data repo.

This PR doesn't do any re-organizing to make the repo more "package"-like and less "app"-like.

Any advice on testing workflows would be much appreciated!

## Type of change

- [X] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

N/A

### Development

These boxes should be checked by the submitter prior to merging:

- [ ] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Review by jessex — COMMENTED** [review]
No in-depth remarks from my quick scan! Just two high-level questions:
- Is that marketplace app or the package publishing expected to generate new costs? If so, any idea of their order of magnitude?
- Is the published package going to be public or private? If public, can you send a link to where it would live?

**Comment by nbhargava** [comment]
Using a separate GitHub marketplace app doesn't generate any distinct costs. I think that actually this approach should be free since GH Actions says that their pricing is free for open source repos (which this one as of right now still is).

The published package will be public and it will be hosted by GitHub Packages (also free for open source repos). I believe there will be a link in the sidebar of the repo where our package will be accessible, just like with releases:
image

**Comment by jessex** [comment]
Great, no worries from me!

**Review by ohaibbq — APPROVED** [review]
Lets try it out!

**Pull request merged**
